### ISSUE TITLE
Slack channel not valid

### ISSUE THREAD

**Issue by Swampcritter** [rocky-linux/rocky#112]
Under the Contributing section on the README, the Slack channel/invite is showing up as not valid:

This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

https://github.com/rocky-linux/rocky#contributing

**Comment by santium** [comment]
The projects site has a working link:

https://slack.rockylinux.org/

**Comment by hbjydev** [comment]
Closing, the Slack link will be updated everywhere soon.

For now, an always-working link will be on https://rockylinux.org
