### ISSUE TITLE
Commit convention 

### ISSUE THREAD

**Issue by Zaragon-AQ** [rocky-linux/rocky#116]
Hi guys, I suggest these rules https://www.conventionalcommits.org/en/v1.0.0/

**Comment by hbjydev** [comment]
Absolute ++ from me, but we'd need a way to enforce it. GitHub Actions or a bot of some kind. Reject PRs until they've rewritten their commit history with the correct commit message style.

**Comment by Zaragon-AQ** [comment]
@hbjydev Something like this? https://github.com/marketplace/commit-lint

**Comment by hbjydev** [comment]
Yes, I was thinking something like that.

**Comment by DemiMarie** [comment]
Would it be possible to require that commits are GPG signed?

**Comment by tevosouza** [comment]
I'm interested on this project and absolutely agree with commit rules and enforce gpg signature in the commits.

**Comment by jamescassell** [comment]
I think it's overkill to sign commits. Generally it's sufficient to sign tags, IMO.

**Comment by DemiMarie** [comment]
@jamescassell While I strongly support requiring signed commits, that doesn’t mean that signing a commit should be an involved process.  I would expect that the commit signing key has no passphrase and is conveniently accessible.

**Comment by hbjydev** [comment]
> @jamescassell While I strongly support requiring signed commits, that doesn’t mean that signing a commit should be an involved process.  I would expect that the commit signing key has no passphrase and is conveniently accessible.

Absolutely not, signing commits with a shared key will *never* happen here. People would have to use their own GPG keys.

I think it would be good to require it, though, to ensure security and identity in the project. (Cc @NeilHanlon @nazunalika @gmkurtzer)

**Comment by NeilHanlon** [comment]
Agreed. I'm not sure what the point of signing using a shared key is, though I'm interested to hear if this is actually something that is done?

Signing commits is done to validate that the person doing the signing is who they say they are. A shared key with no passphrase completely sidesteps that.

Anything which touches production is going to have a multi-eye review, and I am leaning towards both signed tags as well as signed merges to main (manually).

Definitely lots to talk about and formulate plans on.

**Comment by DemiMarie** [comment]
> Signing commits is done to validate that the person doing the signing is who they say they are. A shared key with no passphrase completely sidesteps that.

“Conveniently accessible” means to the person whose key it is.  A shared key is a terrible idea for the reason you mentioned.

What I meant is that making a signed commit should not be more difficult than making an unsigned commit.  I have Git configured to automatically sign all commits, for example.  And I rely on the full disk encryption to protect my key, rather than having a passphrase on it.

I use and develop QubesOS, and use the split GPG support that comes with that operating system.  I wholeheartedly recommend that the Rocky Linux developers do the same, but even a key that is readable by git is better than nothing.

**Comment by hbjydev** [comment]
Okay -- I think I'm willing to take commit conventions and trial it on the website repo. We can see how it goes on there, and see if it's something we want to proceed with.
