### ISSUE TITLE
Development milestones and process

### ISSUE THREAD

**Issue by gmkurtzer** [rocky-linux/rocky#13]
We will start off with short, mid and long term goals:

* **Short term **(2 months): We need to get a release out there for testing and usage so the community can prepare for testing and migrations (12 months is not a long time). This release will include package repositories, mirrors, as well as an installer. Since it is unlikely we will have all of the RPM package autobuilder infrastructure worked out at this point, we will leverage existing CentOS binaries as possible. Signed RPMS will come from both Rocky as well as CentOS.

* **Mid term** (6 months): The Rocky team will continue developing and building the underlying operating system and updates as necessary. By this point, we anticipate having our testing infrastructure up and automatic build infrastructure running and Rocky will be ready for enterprise and cloud deployments. Rocky as an organization will be accepting donations to help with infrastructure but will be strictly not-for-profit and will thus have organization structure solidified.

* **Long term** (12 months and beyond): Special Interest Groups, financial sustainability (via corporate sponsorships and individual donations), community advocates, board of advisors, etc...

**Comment by greg-hellings** [comment]
Put me in coach! What can I do to help?!
