### ISSUE TITLE
Licensing definition and COPYING files needed

### ISSUE THREAD

**Issue by ahappyyodeler** [rocky-linux/rocky#14]
This repository (along with many of the brand-new rocky-linux group) needs a license defined and COPYING file applied before many people can start contributing to or using them. I'm not sure what is an appropriate licence (GPL? Apache? MIT?), but without one, it is both ambiguous and many corporate entities assume "all rights reserved" without a clear open source license.

I'm closing https://github.com/rocky-linux/infrastructure/issues/6 and putting this here for a more top-level approach to license management so that the repositories can remain consistent.

**Comment by Addvilz** [comment]
There is nothing to license here yet, and this should probably be tracked on per-project basis.

**Comment by pxdnbluesoul** [comment]
Noting #47 extends the scope of this to assets contributed. The directive for code is BSD License whenever possible.

(While this is _technically_ out-of-scope for the rocky repo we have archived the organization repo so I want to leave this open until it's captured by project management and actioned.
