### ISSUE TITLE
"Rocky Linux Logo" img is broken

### ISSUE THREAD

**Issue by jorp** [rocky-linux/rocky#141]
Might have been due to the recreation of: https://github.com/rocky-linux/branding

**Comment by hbjydev** [comment]
Someone needs to update all of the READMEs to use `https://raw.githubusercontent.com/rocky-linux/branding/main/logo-text-light%402x.png`. I don't have time atm, who could do it instead?

**Comment by jorp** [comment]
> Someone needs to update all of the READMEs to use `https://raw.githubusercontent.com/rocky-linux/branding/main/logo-text-light%402x.png`. I don't have time atm, who could do it instead?

yeah, I'll do it
