### ISSUE TITLE
Find partners willing to donate resources (compute/bandwidth etc)

### ISSUE THREAD

**Issue by Rorasaurus** [rocky-linux/rocky#15]
# Thank you for your support!
Please send offers of support to hello@rockylinux.org, or visit https://wiki.rockylinux.org/contributing.

**Comment by saberph** [comment]
We can provide it.

Let me know what you need exactly and we can build a private cloud for it.

Regards,
Saber
CTO @PlanetHoster

**Comment by Rorasaurus** [comment]
@saberph thanks so much for responding so quickly.

The project is still very much in the early planning, but we'll certainly keep you updated with what we'd need.

**Comment by timelordx** [comment]
These guys are saying they have all the infrastructure already available. What about partnering with them?

- [Announcing Open-sourced & Community-Driven RHEL Fork by CloudLinux](https://blog.cloudlinux.com/announcing-open-sourced-community-driven-rhel-fork-by-cloudlinux)

I desperately want any of you guys to succeed. You might have a better chance working together.

**Comment by Rorasaurus** [comment]
@timelordx absolutely, it would be better if we worked together. @gmkurtzer has already reached out to them to discuss collaboration.

**Comment by pedroalvesbatista** [comment]
We from @labirintlabs would like to help with some funding soon, and until June/2021 we have oud MDC (Micro Data Center) Tier-0 up and running, we can host some applications and workloads. As we're totally R&D driven, getting some HPC and other research sandboxes would help to improve Rocky utilities for labs and research centers.

**Comment by viniciusferrao** [comment]
I can provide a mirror in Brazil when the distribution needs it.

**Comment by macropin** [comment]
Hi from @ascendos. Let me know what you specifically need. I can put you in contact with community members that previously assisted Ascendos project.

**Comment by minusmillionaer** [comment]
Hi,
we can provide some servers for build infrastructure and host mirros for germany. Please let me know if you need it.

Best
Giuliano

**Comment by sleach** [comment]
Fastly provides free CDN for open source projects (including many Linux distro's etc.)

https://www.fastly.com/open-source

**Comment by pedroalvesbatista** [comment]
> I can provide a mirror in Brazil when the distribution needs it.

Cool, we can offer one too ! So in Latin America we're about to two mirrors in the scene :D

**Comment by BlackOfMing** [comment]
I can provide a mirror in Asia too.

**Comment by jezekus** [comment]
We can provide build servers and host mirror in Czech Republic. Let me know when interested.

Regards

**Comment by Razva** [comment]
Count us in for Mirrors and Compute resources.

**Comment by marcin-github** [comment]
If you need something with rather small resources I can help too.

**Comment by okhosting** [comment]
Hosting provider here, also web design services, app and software development, can provide website, logo design, corporate identity, some storage and servers, and web marketing.

Glad to be of service.

**Comment by brianclemens** [comment]
# Thank you for your support!
Please send offers of support to hello@rockylinux.org, or visit https://wiki.rockylinux.org/contributing.
