### ISSUE TITLE
Merge/collaborate with existing/newly born similar efforts

### ISSUE THREAD

**Issue by nmusatti** [rocky-linux/rocky#2]
If there is one thing we do not need, that is one RHEL derived distro for each single user. Please before starting out new efforts, check what is already starting and what has been there for a long time. I'm thinking of [Open Enterprise OS](https://github.com/Open-Enterprise-OS/oeos) and, even more, [Scientific Linux](https://scientificlinux.org/)

**Comment by Learloj** [comment]
Have you clicked that Open Enterprise OS link? :-)

**Comment by nmusatti** [comment]
So my identical issue, opened on their repo, worked!

**Comment by bensallen** [comment]
Scientific Linux announced a while back that they’re not doing a EL8 release https://listserv.fnal.gov/scripts/wa.exe?A2=SCIENTIFIC-LINUX-ANNOUNCE;11d6001.1904

**Comment by boothb** [comment]
What about Springdale Linux? http://springdale.math.ias.edu/

Is there some possibilty for synergy?

**Comment by opoplawski** [comment]
> Scientific Linux announced a while back that they’re not doing an EL8 release https://listserv.fnal.gov/scripts/wa.exe?A2=SCIENTIFIC-LINUX-ANNOUNCE;11d6001.1904

Although at the time CentOS 8 was seen as the viable replacement for a SL8.  Personally I'm hoping for a revived SL8.

In any case, before starting out on one's own, it makes sense to try to coalesce a community.

**Comment by philregier** [comment]
Pretty sure in the early days of CentOS we also had WBEL, Tao, and SL just to name the major ones.  There was some push and pull, and not all survived, but I don't feel like the parallel efforts and slight differences in philosophy harmed the ecosystem or the eventual coalescence around CentOS.  If anything I think the fact that people were trying different things probably helped in the long run.

Still I don't challenge the premise, and certainly like the idea of proactive communication.

**Comment by nmusatti** [comment]
> Pretty sure in the early days of CentOS we also had WBEL, Tao, and SL/FermiLinux just to name the major ones. There was some push and pull, and not all survived, but I don't feel like the parallel efforts and slight differences in philosophy harmed the ecosystem or the eventual coalescence around CentOS. If anything I think the fact that people were trying different things probably helped in the long run.
> 
> Still I don't challenge the premise, and certainly like the idea of proactive communication.

The one, major harm that may not have mattered much back then, but does matter now is dispertion of resources: volunteer time, machine time, etc.

**Comment by luctimm** [comment]
> 
> 
> What about Springdale Linux? http://springdale.math.ias.edu/
> 
> Is there some possibilty for synergy?

I've tried both Springdale and SL in the EL6 days, when they were still named PUIAS. It was a very nice distro at that time, but I ended up starting using only CentOS after the EL7.

**Comment by dokuhebi** [comment]
> 
> 
>There was some push and pull, and not all survived, but I don't feel like the parallel efforts and slight differences in philosophy harmed the ecosystem or the eventual coalescence around CentOS.
>

If I recall, one reason leading to Scientific Linux shutting down was because their goals were identical to CentOS, i.e. a binary compatible "clone" of RHEL.  Their decision to go with CentOS8 came from their realization that there was no point in duplicating effort.  With the CentOS change, I think reaching out to the team who worked on Scientific Linux would be beneficial.

(As an aside, I'm not really gelling with the Rocky Linux name, and would love for the Scientific Linux name to be revived, even if it were with a different team.)

**Comment by chadbrewbaker** [comment]
Features I care about:

0) Nightly build of latest gcc/llvm/cmake/autotools.
 
1) dnf needs to be able to build succinct container images from just whitelisted packages.

2) Would be nice if dnf also worked on OS X so brew for xnu packages could be deprecated with a real distro.

3) WSL2 linux kernel as an artifact with solid eBPF support.

4) dnf using https://github.com/StanfordSNR/gg as the default builder. No more waiting on compiles for end users. The distro itself can have an prioritized EC2 Batch spot queue and the throughput actively scaled by donation levels.

**Comment by philregier** [comment]
> > There was some push and pull, and not all survived, but I don't feel like the parallel efforts and slight differences in philosophy harmed the ecosystem or the eventual coalescence around CentOS.
> 
> If I recall, one reason leading to Scientific Linux shutting down was because their goals were identical to CentOS, i.e. a binary compatible "clone" of RHEL. Their decision to go with CentOS8 came from their realization that there was no point in duplicating effort. With the CentOS change, I think reaching out to the team who worked on Scientific Linux would be beneficial. I'm almost certain that Fermilab, etc., is reevaluating their decision, and it'd be nice to hear their thoughts on where they're looking to go in the future for their needs.
> 
> (As an aside, I'm not really gelling with the Rocky Linux name, and would love for the Scientific Linux name to be revived, even if it were with a different team.)

Point well made about SL; I'm guessing GMK knows plenty of people there already.  ;)

Regarding Rocky, I'm hoping it's a tribute to one of the original cofounders of CentOS (and its less long-lived sister project CaOS), may he rest in peace.  He was my first professional mentor, and opened my eyes to worlds I may never have experienced otherwise.  I owe my entire Linux+HPC career to Rocky, and I miss him dearly.  I'm guessing the others who remember him may also have strong feelings about the name.

**Comment by DrDaveD** [comment]
Yes, that is where the name is from.

**Comment by rraines** [comment]
One of the reasons I could sell the idea to use CentOS or Scientific Linux to customers/workplace is the names. They had a professional ring to them.  As much of a non-issue the name is for technical folks, the business/security side of the team can be picky. I had Ubuntu challenged because it had a foreign name and that customer was worried about "security". Alpine and some other niche OSs were thought to be unreliable pet projects because of names perceived unprofessional. Stupid, but a reality.

**Comment by deajan** [comment]
@rraines Fair enough. "Rocky Linux" sounds great but probably not in the ears of a CEO. It could maybe be a nickname, or there could be a more enterprise level nickname so we'll keep the "Rocky" spirit but also have something a CEO can identify with. We could try to find some "enterprise" names like, let's say "ENC Linux" where ENC is a recursive, ie ENC is not CentOS.

**Comment by chintan-mishra** [comment]
How about RockSELinux?

We can call it Rock Solid Enterprise Linux. We can pronounce it as RoxyLinux or RockyLinux.

**Comment by deajan** [comment]
> How about RockSELinux?
> 
> We can call it Rock Solid Enterprise Linux. We can pronounce it as RoxyLinux or RockyLinux.

Sounds good too, but we'll get "SELinux" trademark issues maybe.

**Comment by deajan** [comment]
RNROS, Rocky is Not Red OS, whatever. I like the idea of the recursive acronym.

**Comment by chintan-mishra** [comment]
REL - Rocky Enterprise Linux
And some devs already tag their release like `rel-v-2.2.0-rc.1`

**Comment by deajan** [comment]
@chintan-mishra one letter away from a lawsuit :(

**Comment by velenux** [comment]
> @rraines Fair enough. "Rocky Linux" sounds great but probably not in the ears of a CEO. It could maybe be a nickname, or there could be a more enterprise level nickname so we'll keep the "Rocky" spirit but also have something a CEO can identify with. We could try to find some "enterprise" names like, let's say "ENC Linux" where ENC is a recursive, ie ENC is not CentOS.

maybe "Rocky" could be the codename for the first release?

**Comment by deajan** [comment]
REALOS - Rocky Enterprise Accurate Linux Operating System
RWH - Rocky Without Hat (ok that's just for the fun)

We'd also have to check that those acronyms / names aren't some bad words in other languages ;)

**Comment by Learloj** [comment]
In case someone missed it: https://blog.cloudlinux.com/announcing-open-sourced-community-driven-rhel-fork-by-cloudlinux

**Comment by nmusatti** [comment]
I hope these efforts will coalesce into a single distribution. It doesn't make sense to waste resources on multiple projects.

**Comment by DjRakso** [comment]
Regardless whatever the name will be, It will be a great development!

If you would like a random Suggestion: Another Rocky Enterprise Community-driven OS (AREC OS or AROCK OS)

**Comment by kronenpj** [comment]
[CloudLinux](https://blog.cloudlinux.com/announcing-open-sourced-community-driven-rhel-fork-by-cloudlinux) announced today:
...
> As we already maintain CloudLinux OS, we plan to release a free, open-sourced, community-driven, 1:1 binary compatible fork of RHEL® 8 (and future releases) in the Q1 of 2021. We will create a separate, totally free OS that is fully binary compatible with RHEL® 8 (and future versions). We will sponsor the development & maintenance of such OS. We will work on establishing a community around the OS, with the governing board from members of the community.
...

**Comment by TekMonksGitHub** [comment]
We rely heavily on CentOS and will be starting and releasing MonkOS which will be a fork of Enterprise Linux. Happy to combine efforts as we are looking for both volunteers or people who want to be paid for their efforts. 

https://monkos.org

**Comment by magicdrums** [comment]
> Regardless whatever the name will be, It will be a great development!
> 
> If you would like a random Suggestion: Another Rocky Enterprise Community-driven OS (AREC OS or AROCK OS)

Regardless of the name there is already something said about him, I think this decision should be respected ...

"Thinking back to early CentOS days... My cofounder was Rocky McGaugh. He is no longer with us, so as a H/T to him, who never got to see the success that CentOS came to be, I introduce to you...Rocky Linux"
— Gregory Kurtzer, Founder

**Comment by arctus-io** [comment]
@gmkurtzer Have conversations with the CloudLinux folks gone anywhere? Is that looking like a viable partnership?

**Comment by quazardous** [comment]
> 
> 
> No chance he was ever referred to as "Rock"? - because "Rock Linux" evokes some good emotions concerning stability and longevity to me.

RockOS ?

**Comment by quazardous** [comment]
> 
> 
> @gmkurtzer Have conversations with the CloudLinux folks gone anywhere? Is that looking like a viable partnership?

Not partnership but sponsorship (i mean we don't want to start over in 5 years)

**Comment by protonesso** [comment]
@nmusatti @ataraxialinux :^)
