### ISSUE TITLE
where to downloads isos?

### ISSUE THREAD

**Issue by jiatongwu** [rocky-linux/rocky#20]
i will never use centos  
fuck microsoft fuck apple fuck redhat

we are linux  
we are gnu

**Comment by different55** [comment]
Nobody's GNU here, frick off. It's an operating system not an identity. Project's not even up and running yet.

**Comment by alecthegeek** [comment]
Maybe some community guidelines are needed?

**Comment by hbjydev** [comment]
+1 @alecthegeek 
I'm closing this issue.
