### ISSUE TITLE
BTRFS support?

### ISSUE THREAD

**Issue by kevhawk2914** [rocky-linux/rocky#22]
We have a number of systems running Centos 7 and 8 the announcement of the removal of BTRFS by Redhat was a major disappointment for many.

For us it meant we didn't have a direct replacement once Centos 7 becomes EOL and we were holding out to see if it would be added back. 

I'm sure many others are having similar concerns and hopefully this can be added back!

**Comment by viniciusferrao** [comment]
This os definitely not the goal here. The goal is to be 1:1 with RHEL.

Anyway, Fedora 33 have default btrfs once again. Perhaps RHEL9 will come back with btrfs.

**Comment by hbjydev** [comment]
As Fedora feeds into COS Stream, which in turn goes into RHEL, I expect we should see BTRFS support in RHEL 9, yeah, sounds about right @viniciusferrao

**Comment by kevhawk2914** [comment]
Unfortunate, hopefully we will see Rocky 9 before Centos 7 goes EOL. We were hoping not going to have to make the move to Ubuntu Server.

**Comment by hbjydev** [comment]
@kevhawk2914 Are alright for me to close this issue if your question's been answered?

**Comment by k5bpc** [comment]
What are the specific features that give you value with btrfs?  Perhaps there is another native way to get the feature set you require in EL8.

**Comment by kevhawk2914** [comment]
It's used in many machines in a two disk BTRFS mirror as a replacement to the instability of Linux MD we had for many years.

This means native boot support for BTRFS is a requirement, along with container support and snapshots for internal systems. While it is possible to make it work via custom kernels and repos this is not a long term support road we wish to follow.

We have explored many options in the past and no others meet these strict requirements for our application. Without BTRFS we will have to abandon RHEL.

I'll close this issue, we will keep a close eye on the progress of this in hopes a solution can be reached before we have to make the move to another base distro entirely.
