### ISSUE TITLE
Source of information

### ISSUE THREAD

**Issue by rubenvarela** [rocky-linux/rocky#24]
The readme says,

> ## Stay Informed
> 
> * [Slack](https://join.slack.com/t/hpcng/shared_invite/zt-gy0st6mt-ijgUaSvfdeEOhfXXfIstrQ)
> * [Forum](forums.rockylinux.org/)
> * [IRC](https://webchat.freenode.net/?channels=rockylinux)
> * [GitHub](https://github.com/rocky-linux/)
> * [Twitter](https://twitter.com/rocky_linux)
> * [Reddit](https://www.reddit.com/r/RockyLinux)
> * [Matrix](https://matrix.to/#/+rockylinux:matrix.org)

This just feels really fragmented.

Do I have to join/follow all of these to know what’s going on?

**Comment by sentabi** [comment]
just wait a bit, it takes time to prepare everything. The project's not even up and running yet.

I follow Twitter and GitHub

**Comment by aonsyed** [comment]
If you want to stay updated on the progress, probably twitter, if you want to see progress, GitHub, if you wan to be a part of it, Slack

**Comment by hbjydev** [comment]
@aonsyed has the right answer here, but this is definitely something to note. I won't keep this up as an issue but I'll move it to a discussion.
