### ISSUE TITLE
Another useless making wheel project

### ISSUE THREAD

**Issue by copslock** [rocky-linux/rocky#25]
Why people like wasting time on making complete replica ?The real urgent project like [O-RAN](https://wiki.o-ran-sc.org/display/ORAN) lacks of contribution developers,while so many guys focusing on constantly reinventing duplicated wheels?

**Comment by shiz0** [comment]
CentOS was a useless replica project then, too? For that, many people use it though. 
And given the response from the community to RH killing it in it's current form, a future alternative really IS needed.
Maybe not by you personally, but who are you to judge in the first place...?

**Comment by jhngrant** [comment]
Reinventing the wheel means duplicating something that already exists. CentOS obviously addressed a need. There is now a gap. Rocky Linux will hopefully address that need and fill the gap.

**Comment by hbjydev** [comment]
I'm closing this, there's no need for this to be an issue here.
