### ISSUE TITLE
Slack link not available anymore

### ISSUE THREAD

**Issue by rascasoft** [rocky-linux/rocky#28]
As of today, it is impossible to join the Slack workspace using the link provided in the README, so [`https://join.slack.com/t/hpcng/shared_invite/zt-gy0st6mt-ijgUaSvfdeEOhfXXfIstrQ`](https://join.slack.com/t/hpcng/shared_invite/zt-gy0st6mt-ijgUaSvfdeEOhfXXfIstrQ).

Maybe a new one needs to be generated.

Thanks.

**Comment by hbjydev** [comment]
Discussing this on Slack currently.

Do you need another temporary one for now? @rascasoft

**Comment by opencloudengineer** [comment]
I would love to contribute to this project and I am really eager to find out the hows/whens of this project in regards to future development.
In short, I have a lot of queries that Slack would be a better place to resolve than making Github issues.
@hbjydev I would love to join the slack channel now.

**Comment by rascasoft** [comment]
> Discussing this on Slack currently.
> 
> Do you need another temporary one for now? @rascasoft

Yes, thanks, might be useful also for others.

**Comment by hbjydev** [comment]
https://join.slack.com/t/hpcng/shared_invite/zt-k5z04bsh-1uqpaD1NsYVP73vzc3uKdQ @rascasoft @opencloudengineer

**Comment by Addvilz** [comment]
https://github.com/outsideris/slack-invite-automation for automating invites and to avoid the invite link limitations.

**Comment by amit177** [comment]
I can host an instance with that to handle invites.
Do we have approvals from everyone? maybe suggestions for other similar invites if this one isn't good enough?

**Comment by jonnysowards** [comment]
The website rockylinux.org has a link to the slack.

**Comment by hbjydev** [comment]
This has been fixed now. Closing...

**Comment by jorp** [comment]
We've officially moved to Mattermost, join us: https://chat.rockylinux.org
