### ISSUE TITLE
Announcement for help / donations / hosting / etc

### ISSUE THREAD

**Issue by deajan** [rocky-linux/rocky#3]
Gregory,

Thanks for stepping up with not leaving the original community fade.
I think most of us can chip in with donations, bandwidth, server ressources and whatever is needed.

Do you have a list of requirements and a donation page ?

Best regards.

[EDIT] Found this https://github.com/rocky-linux/organization/wiki/Contributing [/EDIT]

**Comment by netroby** [comment]
@deajan The slack seems need to invite to join. would you please invite me ?

**Comment by deajan** [comment]
@netroby asking the wrong guy, I emailed the guys on the list to see whether we could give some help

**Comment by DrivenDemon** [comment]
I am excited to see where this all goes.

**Comment by rickconlee** [comment]
I would like to help in whatever way I can. How do I get involved?

**Comment by edoherreraCL** [comment]
Thanks for the opportunity to continue with a new distro.

**Comment by EarlRamirez** [comment]
I will like to volunteer in this endevour

**Comment by okhosting** [comment]
We can provide some servers and storage, glad to help in this IMPORTANT endeveour!

**Comment by okhosting** [comment]
We can also provide design services, like a nice logo for the project, a corporate identity and a nice website, free of charge.

**Comment by DevLomoSE** [comment]
I'll be glad to help in whatever I can, How I can be volunteer?

**Comment by jonnysowards** [comment]
Here to help in any way possible.

**Comment by mooyun** [comment]
I am very excited,very well

**Comment by oubayun** [comment]
Rocky Linux Chinese Community：www.rockylinux.cn，Support hpcng

**Comment by jorp** [comment]
> We can also provide design services, like a nice logo for the project, a corporate identity and a nice website, free of charge.

Please reach out to the #rocky-branding channel on [slack](https://hpcng.slack.com/)

**Comment by manngo** [comment]
At the risk of sounding like me-too, I would also like to offer my help.

I am a developer, but not in the areas directly related to building an OS. I am more focused on Web development (not in the artistic sense, but in the coding sense) and database.

I’m also fairly literate of there’s any documentation I can help with.

I’ve been a great fan of CentOS for a long time, and WBEL before that, so anything we can do to help …

**Comment by JackKimUSA** [comment]
I would like to offer my help.

I am a system engineer. I can validate the rocky linux OS with server, IB card, 10G card, M.2 SSD,  GPU, etc.

Thank you.

**Comment by marmile** [comment]
Count me in. Sysadmin background, tools and processes, some development skills.

**Comment by noncatalyst** [comment]
I also help you. 
I'm sys-admin engineer and sometime program.

Count me in, Please.

**Comment by Chewbury** [comment]
I'm up for helping too. Sysadmin of serveral HPC clusters in acadaemia. Continuing availability of a stable RHEL derived system is very important to us.

**Comment by bdowne01** [comment]
Count us in.  We are an ISP with servers, colocation, and bandwidth.  CentOS was important in the success of our business and we definitely want to help give back now they've changed direction.

**Comment by jezekus** [comment]
Also offering help in the infrastructure area.
We could provide resources for hosting mirror with high capacity network.

**Comment by wernermarcel77** [comment]
I can help as sysadmin. And with what I had to learn in the last 2 decades about all possible integration in any tools.

**Comment by okhosting** [comment]
> > We can also provide design services, like a nice logo for the project, a corporate identity and a nice website, free of charge.
> 
> @okhosting
> 
> Please reach out to the #rocky-branding channel on [slack](https://hpcng.slack.com/)

Sure thing, thanks!

**Comment by okhosting** [comment]
> > We can also provide design services, like a nice logo for the project, a corporate identity and a nice website, free of charge.
> 
> @okhosting
> 
> Please reach out to the #rocky-branding channel on [slack](https://hpcng.slack.com/)

@jorp I tried to but it seems there is no registration link? Sorry I don't use slack but I can't register to that worspace anywhere it seems
