### ISSUE TITLE
Investigate FOSS productivity tools

### ISSUE THREAD

**Issue by jorp** [rocky-linux/rocky#31]
https://www.atlassian.com/software/views/open-source-license-request

**Comment by ebebpl** [comment]
Bad decision :) . There are hundreds of very large open source projects using JIRA as it is one of the top tools out there. If Atlassian makes life difficult in future it may not be a heavy lift to export/import all the issues from JIRA to whatever is the next best tools that comes along.

**Comment by NeilHanlon** [comment]
> Bad decision :) . There are hundreds of very large open source projects using JIRA as it is one of the top tools out there. If Atlassian makes life difficult in future it may not be a heavy lift to write some scripts to export/import all the issues from JIRA to whatever is the next best tools that comes along.

Time will tell.

There are also plenty of projects (Linux foundation et al, to name some) using open project.

"not a heavy lift" is a lot easier to say than it is to accomplish. Jira is a pain in the ass.
