### ISSUE TITLE
Researching initial hosting, and setting up initial servers for IDM solution.

### ISSUE THREAD

**Issue by jorp** [rocky-linux/rocky#38]

**Comment by NeilHanlon** [comment]
> > 
> > 
> > > The [OSU Open Source Lab](https://osuosl.org) is also available for providing some infrastructure help.
> > 
> > Thanks! I filled out a request yesterday and have been in contact with Lance.
> 
> I believe that's Lance you just replied to. 😆 

I should get some sleep.


*looks at time*



I should really get to sleep.


Sorry lance <3

**Comment by siruslan** [comment]
Hello, I'm co-founder of Jelastic. Our [Cloud Union](https://jelastic.cloud) of independent cloud hosting providers has over 100 data centers around of the world. Some providers have already expressed their interest to support this initiative. I will send message to hello@rockylinux.org to get more details about requirements.

**Comment by aevtech** [comment]
Hello,

We at AEVTech (https://www.aevtech.com/) and Imani Systems (https://www.imani-system.com) would like to assist with infrastructure and mirrors. We can provide infrastructure in the following locations:

USA (Atlanta, New York, New Jersey, Chicago, Dallas, Los Angeles, Miami, Seattle and Silicon Valley)
Toronto Canada
Amsterdam Netherlands
Paris France
Frankfurt Germany
London United Kingdom
Tokyo Japan
Seoul South Korea
Singapore
Sydney Australia

We will send an e-mail to hello@rockylinux.org as well and look forward to helping anywhere possible.

Thank You!

info@aevtech.com
info@imani-systems.com

**Comment by vielmetti** [comment]
Equinix Metal is interested in contributing resources to the project - I have been in touch by email as well.
