### ISSUE TITLE
Document process for forking & rebuild RHEL

### ISSUE THREAD

**Issue by kagesenshi** [rocky-linux/rocky#4]
So that knowledge can be propagated for others may do so if similar stuff happens in future .. or also for others who may want to fork RHEL/rocky for some specific purpose.

**Comment by koachan** [comment]
The project could probably follow the format of [Part V of NetBSD's guidebook](https://www.netbsd.org/docs/guide/en/part-compile.html) or [OpenBSD's release(8) manual page](https://man.openbsd.org/release), giving step-by-step guide on:

- Where and how to get the SRPMs;
- How to set up a build environment (incl. if it can be done on non Fedora/EL-derived distros);
- How to replace branding (if using upstream sources);
- How to build the binary RPMs; and
- How to generate installable images and package repositories out of those RPMs.

**Comment by libertas** [comment]
This is absolutely very important to the community and the public.
I thought about working on my on distribution yesterday so I googled it but didn't found out how they got the source code from RHEL.

**Comment by dvershinin** [comment]
@libertas one of the ways to fetch SRPMS would involve a dedicated machine subscribed with a developer RHEL license, and simply fetching/reposyncing SRPMS from `-source` repos like one of these:

```
[rhel-8-for-x86_64-baseos-source-rpms]
name = Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Source RPMs)
baseurl = https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/baseos/source/SRPMS
enabled = 0
gpgcheck = 1
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
sslverify = 1
...
```

**Comment by hbjydev** [comment]
I have a RHEL developer subscription I could easily donate allocations from.

**Comment by kallisti5** [comment]
Technically RedHat is supposed to offer unencumbered access to SRPM's (especially GPL sources).  I could see the argument "if you don't have access to our binaries, you don't need access to the sources" from Red Hat.... However anyone with any kind of RHEL subscription could legally upload SRPM's to rocky-linux.

IPFS is pretty neat and does dedup with checksuming of files. If folks dumped SRPM's here, anyone could help host them, and anyone could access them via any IPFS gateway (like https://cloudflare-ipfs.com)

**Comment by jamescassell** [comment]
Does RH prohibit customers from sharing the SRPMS? Otherwise, any customer could technologically sync them somewhere public. RH stopped publishing RHEL SRPMS starting with RHEL 7, IIRC, telling folks to get them from CentOS instead.

**Comment by kallisti5** [comment]
https://www.reddit.com/r/redhat/comments/kcbuba/i_have_an_active_developer_subscription_where_can/

http://ftp.redhat.com/redhat/linux/enterprise/8Base/
http://ftp.redhat.com/redhat/linux/enterprise/7Server/en/os/README

Getting SRPM's feels like it's going to be a fight

**Comment by koachan** [comment]
> anyone with any kind of RHEL subscription could legally upload SRPM's to rocky-linux

> Does RH prohibit customers from sharing the SRPMS?

It's technically legal, but I keep seeing rumors (in HN, reddit, etc.) that they would sumarrily terminate the subscription of someone who publishes raw, RH-branded SRPMS; I can't confirm if this is true, though.
Anyway, the requirement of having a subscription to even start downloading SRPMS is a big obstacle in itself.

> if you don't have access to our binaries, you don't need access to the sources

IANAL but limiting source access to binary-owners only is still allowed under the GPL, no?

**Comment by jkwong** [comment]
Fedora has excellent tutorials in installing koji and using koji to build rpms:
* Overview of koji: https://docs.pagure.org/koji/
* Setting up your own koji instance: https://docs.pagure.org/koji/server_howto/
* Using the koji build system: https://docs.pagure.org/koji/using_the_koji_build_system/
* Building images (installer isos, disk images, containers) in koji: https://docs.pagure.org/koji/image_build/

CentOS doc on koji: https://wiki.centos.org/HowTos/CommunityBuildSystem

**Comment by jasonbrooks** [comment]
The current process for CentOS is documented here: "About/Building_8.x - CentOS Wiki" https://wiki.centos.org/About/Building_8.x#General_Steps

**Comment by es02** [comment]
Why not just grab the sources form git.centos.org?
Afaik RH has no plans to stop publishing them there

**Comment by kallisti5** [comment]
>  Afaik RH has no plans to stop publishing them there

Yeah, my trust of Red Hat is at an all time low.

**Comment by zoobab** [comment]
"Getting SRPM's feels like it's going to be a fight"

IBM could claim copyright infringement over some .spec files?

**Comment by dev2008** [comment]
> IBM could claim copyright infringement over some .spec files?

Especially in the US people can claim whatever they want and force you to spend a lot of money defending the claim no matter how baseless.  Look how long SCO kept their baseless claims in court ......

**Comment by Spacial** [comment]
> > IBM could claim copyright infringement over some .spec files?
> 
> Especially in the US people can claim whatever they want and force you to spend a lot of money defending the claim no matter how baseless. Look how long SCO kept their baseless claims in court ......

could we use the "right to repair" for a fair-use case scenario?

**Comment by bish0polis** [comment]
> Look how long SCO kept their baseless claims in court ......

As an insider on that I have to remind you that you mainly know the IBM-Groklaw spin.  SCO was neither adept nor innocent, but render unto Caesar ...

**Comment by carlwgeorge** [comment]
Red Hat has published additional guidance on using RHEL/CentOS sources.

https://developers.redhat.com/blog/2021/02/03/a-guide-for-using-centos-project-code/
