### ISSUE TITLE
Contributor Agreement

### ISSUE THREAD

**Issue by pxdnbluesoul** [rocky-linux/rocky#47]
Discussion surfaced in branding by @BenAgner  that we should ensure that assets submitted for use by Rocky Linux are covered under the scope of an agreement to release the IP to the Foundation (pending setup) in such a manner that the Foundation can use it in any way it needs to. Tracking ticket for that.

**Comment by pxdnbluesoul** [comment]
Noting also that @brianclemens passed along that @gmkurtzer would prefer code contributions go under the BSD License when possible.

**Comment by hwpplayer1** [comment]
Could you please make a discussion section for all needs ?

**Comment by robbosch** [comment]
> Noting also that @brianclemens passed along that @gmkurtzer would prefer code contributions go under the BSD License when possible.

In order to have an open communications, I think it's a good idea to have a statement what reason there is to choose BSD 3 license instead of, for instance, GPL (v2 and/or later)
