### ISSUE TITLE
Rocky Linux Chinese Community

### ISSUE THREAD

**Issue by oubayun** [rocky-linux/rocky#5]
To show my support, I am going to create Rocky Linux Chinese Community, using the domain name www.rockylinux.cn。

**Comment by oldthreefeng** [comment]
great！

**Comment by zhangguanzhang** [comment]
nice

**Comment by idlesysman** [comment]
Will Rocky be acquired someday in the future

**Comment by fulinjie** [comment]
awesome

**Comment by yangyunzhao** [comment]
It doesn't works

**Comment by jerryjoejj** [comment]
> It doesn't works

It does work！

**Comment by yangyunzhao** [comment]
> > It doesn't works
> 
> It does work！

http://www.rockylinux.cn/ replies 404 not found

**Comment by Sokwva** [comment]
ERR_NAME_NOT_RESOLVED ?

**Comment by cks2015** [comment]
nice

**Comment by CaoDonghui123** [comment]
great

**Comment by liupeng0518** [comment]
nice

**Comment by trendhu** [comment]
> To show my support, I am going to create Rocky Linux Chinese Community, using the domain name [www.rockylinux.cn。](http://www.rockylinux.cn%E3%80%82)

You might consider creating a static page for this domain to display first。

**Comment by yumeplus** [comment]
nice

**Comment by yangjinhe** [comment]
卧槽，牛逼

**Comment by ibakirov** [comment]
> Will Rocky be acquired someday in the future
Project have to create/transform/join into Foundation alike organization to be protected

**Comment by fency12** [comment]
NICE

**Comment by yangjinhe** [comment]
six six six

**Comment by xiangjihan** [comment]
Niubility,that's great!

**Comment by chintan-mishra** [comment]
How about RockSELinux?

We can call it Rock Solid Enterprise Linux. We can pronounce it as RoxyLinux or RockyLinux.

**Comment by wangyu1314** [comment]
Don't use cn domain, thank you.

**Comment by oubayun** [comment]
> > To show my support, I am going to create Rocky Linux Chinese Community, using the domain name [www.rockylinux.cn。](http://www.rockylinux.cn%E3%80%82)
> 
> You might consider creating a static page for this domain to display first。

Yes,It already has.

**Comment by fency12** [comment]
6 6 6

**Comment by trendhu** [comment]
> > > To show my support, I am going to create Rocky Linux Chinese Community, using the domain name [www.rockylinux.cn。](http://www.rockylinux.cn%E3%80%82)
> > 
> > 
> > You might consider creating a static page for this domain to display first。
> 
> Yes,It already has.

So fast

**Comment by maxadamo** [comment]
:+1:  :+1: 
The Trump supporters have put a thumb down to this proposal. There is massive fraud in Rocky Linux, they say.

**Comment by MartinOps666** [comment]
nice

**Comment by CC1E38008** [comment]
well done buddy

**Comment by liangyuanpeng** [comment]
Hope working

**Comment by hellolingxh** [comment]
good job!

**Comment by hbjydev** [comment]
Closing this thread, doesn't need to be an issue

But good job, dude! Rocky will take over the world!

**Comment by ykla** [comment]
Telegram https://t.me/RockyLinuxCN
QQ Group 971363171
