### ISSUE TITLE
Moving this project 

### ISSUE THREAD

**Issue by cybernet** [rocky-linux/rocky#54]
1st, pardon my audacity 😁

What I would like to suggest is to move this project to a dedicated instance of GitLab. 

While there are couple of benefits using GitHub - it’s “free” but not really, the ones that have followed Microsoft recently can only imagine what will it do to the Linux community. 

GitLab is a way better solution than github ( IMO )

I’m willing to contribute with some VMs for the project ( located in Germany )

I will like to know what you think of this proposal. 

I would really appreciate an open mind about the matter and really think about it :)

**Comment by fathonir** [comment]
It just started couples of days ago. And I think start in github its not really bad at all. Github and gitlab now have same feature in the same meaning way. 😁

**Comment by cybernet** [comment]
with gitlab, you own your data!

**Comment by danielnaaman** [comment]
GitHub in my opinion is far more convenient and reliable/durable then a dedicated instance of GitLab, not to mention it looks so much better!

I disagree with this suggestion.

**Comment by derekmwright** [comment]
I'm guessing that they have already had these conversations internally before setting out. You might think that this would be the best time to make a change as it is early on, however you are assuming they overlooked the idea of using a privately hosted Gitlab or even a publicly Gitlab project. These types of issues don't really serve to move the project forward at this point and are just creating additional noise and overhead for moderation.

**Comment by Addvilz** [comment]
At this point in time, there are a slight of significantly more important issues to focus on than service politics. A selection of large open source projects use GitHub to host their source code and have experienced no issue so far, at least not to my knowledge.

> with gitlab, you own your data!

Are you implying that by using GitHub we are somehow surrendering our data or IP? Can you elaborate?

**Comment by cybernet** [comment]
> Are you implying that by using GitHub we are somehow surrendering our data or IP? Can you elaborate?

yes, I am ...

after they realised the potential that linux has and how easy is to sell open source software ... 

one more thing - do you all remember when github was massively under a DDoS attack ?

and then shortly after Microsoft announced that it acquired github  ... - no further comments

**Comment by danielnaaman** [comment]
> > Are you implying that by using GitHub we are somehow surrendering our data or IP? Can you elaborate?
> 
> yes, I am ...
> 
> after they realised the potential that linux has and how easy is to sell open source software ...
> 
> one more thing - do you all remember when github was massively under a DDoS attack ?
> 
> and then shortly after Microsoft announced that it acquired github ... - no further comments

Not trying to be rude, but I think this is what you are looking for: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/deleting-your-user-account

> > Are you implying that by using GitHub we are somehow surrendering our data or IP? Can you elaborate?
> 
> yes, I am ...
> 
> after they realised the potential that linux has and how easy is to sell open source software ...
> 
> one more thing - do you all remember when github was massively under a DDoS attack ?
> 
> and then shortly after Microsoft announced that it acquired github ... - no further comments

And that has to do with what? Do you think GitLab is more resilient to these sort of attacks? These are eventually computers and networks, there are always security breaches and flaws. I have nothing against GitLab but your argument is absurd and has nothing to do with why they should or shouldn't host this project on GitHub.

**Comment by mikeperalta1** [comment]
Github is still incredibly popular, so it may be more beneficial to stay here while the project builds a community and makes progress. Maybe some day off in the future, a switch could be made for one reason or another.

**Comment by ebebpl** [comment]
Github is way more popular than Gitlab still and a dinky VM sitting in someones basement is way more risky than a huge cloud infrastructure like Github which is safer bet long term. Suggest someone close this issue!  https://trends.google.com/trends/explore?geo=US&q=github,gitlab,bitbucket

**Comment by v00v** [comment]
Yeah, keep this on GitHub. Don't move it!

**Comment by brianclemens** [comment]
The project will move to GitLab for several reasons including matching anticipated upstream processes, integration with our identity management, etc. Mirrored repositories will be available on GitHub.

**Comment by cybernet** [comment]
> The project will move to GitLab for several reasons including matching anticipated upstream processes, integration with our identity management, etc. Mirrored repositories will be available on GitHub.

any news on that instance ?
