### ISSUE TITLE
Slack link simplly doesn't work!!

### ISSUE THREAD

**Issue by gpamitranjit** [rocky-linux/rocky#63]
I would love to become the member of Rocky-linux community on slack but unfortunately Slack link doesn't work!!
Could you please update the correct slack link for me to join the community??
Current slack link on rockylinux.org site as well as on github page is as below,
Slack link: https://hpcng.slack.com/join/shared_invite/zt-k5z04bsh-1uqpaD1NsYVP73vzc3uKdQ#/

**Comment by fathonir** [comment]
Doble post with #62 .

**Comment by gpamitranjit** [comment]
Since it's duplicate post i'm simply removing it..
sorry for the confusion...
