### ISSUE TITLE
README.md PT-BR

### ISSUE THREAD

**Issue by ErickRock** [rocky-linux/rocky#68]
Inclusion of Reamdme.md in Brazilian Portuguese

**Comment by vhp1360** [comment]
may I send README in Persian Translation?

**Comment by ErickRock** [comment]
@vhp1360 I believe that if we can facilitate access for someone, we should do it, it's a great idea, come on.

**Comment by vhp1360** [comment]
thanks, and I tried to do my best


[README.fr_IR.zip](https://github.com/rocky-linux/rocky/files/5693268/README.fr_IR.zip)

**Comment by vhp1360** [comment]
sorry, you would not add Persian README?
