### ISSUE TITLE
Rocky Linux and Orgzanization on Github

### ISSUE THREAD

**Issue by ibakirov** [rocky-linux/rocky#7]
I suggest to change project name to **Rocky Linux** and transform to **Rocky Linux** organization on Github to take/book this name while it's available

**Comment by boothb** [comment]
https://github.com/rocky-linux

**Comment by ibakirov** [comment]
Great job @boothb!

**Comment by boothb** [comment]
I had nothing to do with it. It was created yesterday I think.

I am trying to contribute in a meaningful way, but have no experience with building and maintaining a distribution.

**Comment by hbjydev** [comment]
@gmkurtzer Any objections to renaming this to rocky-linux? If not, I'll do that and close this

**Comment by Addvilz** [comment]
Looks like this was done ❤️
