### ISSUE TITLE
expand faq

### ISSUE THREAD

**Issue by mphilipps** [rocky-linux/rocky#74]
hi,
Could someone with some knowledge please expand the faq.

How is rocky-linux going to differ to what Centos used to be? It is not like Centos didn't have community in it's headline.  
What is the desired relationship with RedHat?  
Is there any risk that RedHat could cut of rocky-linux during the rhel 8 release cycle or in the presumably upcoming  rhel 9 release?
What is the expected delay between an update getting into rhel 8 and and rocky?

**Comment by robbosch** [comment]
>How is rocky-linux going to differ to what Centos used to be?
It's not. Intentions are to be the same as CentOS was _before_ it was acquired by RH.

**Comment by brianclemens** [comment]
@mphilipps more information about Rocky Linux is available on the Rocky Linux [website](https://rockylinux.org/) and the communication channels it links to. However, to answer your questions:
- Rocky Linux as a product will not differ from what CentOS used to be. The Rocky Linux Foundation as an organization intends to run the project in a way that safeguards Rocky Linux from a similar demise.
- We desire an amicable relationship with the upstream vendor.
- There is very little risk that the upstream vendor will "cut off" Rocky Linux.
- There is no estimate for that delay, but I expect it will be less than the delay seen in CentOS after our processes mature.
