### ISSUE TITLE
Went through the entire README/repository documentation, but system fails to boot

### ISSUE THREAD

**Issue by ahungry** [rocky-linux/rocky#8]
I went through the README and all other associated repository docs, but I can't seem to get my new Rocky Linux system to boot up.

Is the page missing some documentation?

**Comment by vrindger** [comment]
sounds like you're having a rocky start :D

**Comment by NeilHanlon** [comment]
Are you sure the sha256 sums matched?

**Comment by hbjydev** [comment]
Closing, issue contains many false statements -- the biggest of which is that Rocky Linux isn't already perfect ;)
