### ISSUE TITLE
Donations via PayPal or Patreon

### ISSUE THREAD

**Issue by noob-nine** [rocky-linux/rocky#9]
First of all, i have great respect for the work that has to be done. I like the philosophy and I was in favour with the going-to-be-ripped centOS system, too.
Unfortunately, I lack in skills contributing directly to this project.
Therefore I wanted to ask, if there is/will be some possibilities to donate at least some money (in a monthly period).

**Comment by Uro1** [comment]
Rocky Linux should setup GitHub Sponsors for the organisation, that way people can contribute directly to the project without needing to go offsite from GitHub.

See this article in the GitHub docs for more information: 

https://docs.github.com/en/free-pro-team@latest/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-organization
